basePath: /api/v1
host: localhost:8080
info:
  contact:
    name: Yeison Casado
  description: This API provides subway routes and paths between stations using MBTA
    data.
  title: Subway Routing Service API
  version: "1.0"
paths:
  /healthz:
    get:
      consumes:
      - application/json
      description: Returns the status of the service and MBTA API
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "503":
          description: Service Unavailable
          schema:
            additionalProperties: true
            type: object
      summary: Health check
      tags:
      - Health
  /routes:
    get:
      consumes:
      - application/json
      description: Returns stations, lines, and description for a route between start
        and end
      parameters:
      - description: Start station ID
        in: query
        name: start
        required: true
        type: string
      - description: End station ID
        in: query
        name: end
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get subway route
      tags:
      - Routes
  /subways:
    get:
      consumes:
      - application/json
      description: Returns a list of subway routes with nested stations
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all subway routes with their stations
      tags:
      - Subways
swagger: "2.0"
